version: "3.9"

services:
  loadbalancer:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./deploy/default.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - swoole-network
  app:
    build:
      context: .
    restart: always
    deploy:
      mode: replicated
      replicas: 3
    expose:
      - "9501" # Expose the internal port for Nginx to access
    volumes:
      - .:/var/www
    networks:
      - swoole-network


networks:
  swoole-network:
    driver: bridge
