version: "3.9"

services:
  loadbalancer:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./deploy/default.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - swoole-network
  app:
    build:
      context: .
    restart: always
    deploy:
      mode: replicated
      replicas: 3
    expose:
      - "9501" # Expose the internal port for Nginx to access
    volumes:
      - .:/var/www
    networks:
      - swoole-network
  database:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./deploy/entry/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    ports:
      - "3307:3306"
    networks:
      - swoole-network

networks:
  swoole-network:
    driver: bridge
